//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Osmo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Osmo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap empty {
            get {
                object obj = ResourceManager.GetObject("empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SkinIniSyntax {
            get {
                object obj = ResourceManager.GetObject("SkinIniSyntax", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # This files is based on the official wiki entry for Skinning: https://osu.ppy.sh/help/wiki/Skinning/osu!catch
        ///# Date: 25.05.2018
        ///# Entries are split like this:
        ///#    Name|Suggested SD size|Animatable|Version|Description
        ///#
        ///# Note: Only the name is required. If you want to use different values for different versions, write it like this:
        ///#       ranking-graph.png|1.0:min308x156;min308x148
        ///#       You can specify multiple version for one value like &quot;1.0,2.0:308x148&quot;.
        ///#
        ///#       Animatable: Accepts only  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkinningCatch {
            get {
                return ResourceManager.GetString("SkinningCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # This files is based on the official wiki entry for Skinning: https://osu.ppy.sh/help/wiki/Skinning/Interface
        ///# Date: 25.05.2018
        ///# Entries are split like this:
        ///# Name|Suggested SD size|Animatable|Version|Description
        ///#
        ///# Note: Only the name is required. If you want to use different values for different versions, write it like this:
        ///#       ranking-graph.png|1.0:min308x156;min308x148
        ///#       You can specify multiple version for one value like &quot;1.0,2.0:308x148&quot;.
        ///#
        ///#       Animatable: Accepts only tru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkinningInterface {
            get {
                return ResourceManager.GetString("SkinningInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # This files is based on the official wiki entry for Skinning: https://osu.ppy.sh/help/wiki/Skinning/osu!mania
        ///# Date: 25.05.2018
        ///# Entries are split like this:
        ///#    Name|Suggested SD size|Animatable|Version|Description
        ///#
        ///# Note: Only the name is required. If you want to use different values for different versions, write it like this:
        ///#       ranking-graph.png|1.0:min308x156;min308x148
        ///#       You can specify multiple version for one value like &quot;1.0,2.0:308x148&quot;.
        ///#
        ///#       Animatable: Accepts only  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkinningMania {
            get {
                return ResourceManager.GetString("SkinningMania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # This files is based on the official wiki entry for Skinning: https://osu.ppy.sh/help/wiki/Skinning/Sounds
        ///# Date: 25.05.2018
        ///# Entries are split like this:
        ///#    Name|Description|Multiple sounds
        ///#
        ///# You don&apos;t have to write the extension into the name! (Only a dot at the end)
        ///# Note: Only the name is required. 
        ///#       Multiple sounds: Accepts only true or false. Every other value results in false.
        ///#
        ///# Main Menu
        ///heartbeat.|This plays when the cursor is hovering over the osu!cookie in the main menu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkinningSounds {
            get {
                return ResourceManager.GetString("SkinningSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # This files is based on the official wiki entry for Skinning: https://osu.ppy.sh/help/wiki/Skinning/osu!
        ///# Date: 25.05.2018
        ///# Entries are split like this:
        ///#    Name|Suggested SD size|Animatable|Version|Description
        ///#
        ///# Note: Only the name is required. If you want to use different values for different versions, write it like this:
        ///#       ranking-graph.png|1.0:min308x156;min308x148
        ///#       You can specify multiple version for one value like &quot;1.0,2.0:308x148&quot;.
        ///#
        ///#       Animatable: Accepts only true  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkinningStandard {
            get {
                return ResourceManager.GetString("SkinningStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # This files is based on the official wiki entry for Skinning: https://osu.ppy.sh/help/wiki/Skinning/osu!taiko
        ///# Date: 25.05.2018
        ///# Entries are split like this:
        ///#    Name|Suggested SD size|Animatable|Version|Description
        ///#
        ///# Note: Only the name is required. If you want to use different values for different versions, write it like this:
        ///#       ranking-graph.png|1.0:min308x156;min308x148
        ///#       You can specify multiple version for one value like &quot;1.0,2.0:308x148&quot;.
        ///#
        ///#       Animatable: Accepts only  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkinningTaiko {
            get {
                return ResourceManager.GetString("SkinningTaiko", resourceCulture);
            }
        }
    }
}
